{% set name = "xeus-sqlite" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-sqlite/archive/{{ version }}.tar.gz
  sha256: 644c1262bc4075d48533134cf7b6cd0ce4cd597b6914966526b17621ae60dffc

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - xeus-zmq >=1.0.2,<2.0.0
    - cppzmq
    - zeromq
    - nlohmann_json
    - xtl
    # cpp-tabulate 1.5 is backward incompatible
    - cpp-tabulate >=1.3,<1.5
    - sqlitecpp
    - sqlite
    - xvega >=0.0.10
    - xvega-bindings >=0.0.10
    - xproperty >=0.11.0,<0.12.0
  run:
    - xvega >=0.0.10
    - xvega-bindings >=0.0.10

test:
  commands:
    - test -f ${PREFIX}/bin/xsqlite  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xsqlite.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-sqlite
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for SQLite based on xeus
  doc_url: https://xeus-sqlite.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - jtpio
    - marimeireles
