context:
  version: "0.9.1"
  build_number: 0

package:
  name: xeus-sqlite
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-sqlite/archive/${{ version }}.tar.gz
  sha256: ed936068a3b90d5687fbb1b2fde26787a4f3e1d9f3277b5fda2d5a08cb2c1ce0

build:
  number: ${{ build_number }}
  skip:
    - win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then:
        - make
  host:
    - xeus-zmq >=3.1.1,<4.0.0
    - nlohmann_json
    - nlohmann_json-abi
    - xtl
    # cpp-tabulate 1.5 is backward incompatible
    - cpp-tabulate >=1.5
    - sqlitecpp
    - sqlite
    - xvega >=0.1.3
    - xvega-bindings >=0.1.1
    - xproperty >=0.12.1
  run:
    - ${{ pin_compatible('xvega', upper_bound='x.x') }}
    - ${{ pin_compatible('xvega-bindings', upper_bound='x.x') }}

tests:
  - package_contents:
      files:
        exists:
          - bin/xsqlite

about:
  homepage: https://github.com/jupyter-xeus/xeus-sqlite
  repository: https://github.com/jupyter-xeus/xeus-sqlite
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for SQLite based on xeus
  documentation: https://xeus-sqlite.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - jtpio
    - marimeireles
