context:
  version: "0.8.0"
  build_number: 0

package:
  name: xeus-sqlite
  version: ${{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-sqlite/archive/${{ version }}.tar.gz
  sha256: cac9ac6cb8d37c94e900eba1e357dae6b47e06df707b8670fc85f6a9b5207f2a

build:
  number: ${{ build_number }}
  skip:
    - win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then:
        - make
  host:
    - xeus-zmq >=3.1.1,<4.0.0
    - nlohmann_json
    - xtl
    # cpp-tabulate 1.5 is backward incompatible
    - cpp-tabulate >=1.5
    - sqlitecpp
    - sqlite
    - xvega >=0.1.3
    - xvega-bindings >=0.1.1
    - xproperty >=0.12.1
  run:
    - ${{ pin_compatible('xvega', upper_bound='x.x') }}
    - ${{ pin_compatible('xvega-bindings', upper_bound='x.x') }}

tests:
  - package_contents:
      files:
        exists:
          - bin/xsqlite

about:
  homepage: https://github.com/jupyter-xeus/xeus-sqlite
  repository: https://github.com/jupyter-xeus/xeus-sqlite
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for SQLite based on xeus
  documentation: https://xeus-sqlite.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - jtpio
    - marimeireles
